# -*- coding: utf-8 -*-
"""PROYECTO-MALLA CURRICULAR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mfjiYbt6OtzpB-oKxUOTVtXzthOFjXff

#INFORMACIÓN GENERAL

**Universidad Nacional de San Antonio Abad del Cusco**

**Pensamiento Computacional e Inteligencia Artificial**

Pinto Armacta Higinio Jhunior

Torres Cama Merelin Rubi

Checca Ccolqque Denis Yeison


##PROYECTO : Sistema Didáctico Interactivo en Lenguaje Natural
##Malla Curricular de la carrera de Ingenieria Informatica y de Sistemas

####Enunciado

Desarrollar un Software que ayude a los estudiantes de esta carrera a saber mas sobre el manejo adecuado de la malla curricular. Este software interactivo permitira que mendiante preguntas los estudiantes interactuan y puedan saber el semestre, codigo, creditos y area del curso que llevaran; emulando experiencias de un software inteligente sin implementar algoritmos especificos de IA.

####Implementación
"""

import random

"""####Diccionario de conocimientos"""

# *********************  Datos  ******************************
Cursos= ["Química general","Ecología y Medio Ambiente","Historia Crítica del Perú e Identidad Nacional","Física I","Álgebra y Geometría Analítica","Cálculo I",
         "Fundamentos de programación","Matemáticas Discretas I","Pensamiento Computacional e Inteligencia Artificial","Lingüística y Comunicación Humana","Estadística General","Cálculo II",
         "Algoritmos y Estructura de Datos I","Programación I","Matemáticas Discretas II","Física Aplicada a la Informática","Álgebra Lineal Computacional","Cálculo III",
         "Algoritmos y Estructura de Datos II","Programación II","Organización y Dirección de Empresas","Electrónica y Diseño Digital","Modelos Probabilísticos","Ecuaciones Diferenciales",
         "Análisis y Diseño de Algoritmos","Programación III","Análisis y Diseño de Sistemas de Información","Organización y Arquitectura del Computador","Teoría de la Computación","Métodos Numéricos",
         "Actividades Extracurriculares (Deportes)","Inteligencia Artificial","Fundamentos y Diseño de Bases de Datos","Sistemas Operativos","Electivo","Modelado y Simulación",
         "Ciencia de Datos","Aprendizaje Automático","Metodología de Desarrollo de Software","Redes de Computadoras I","Electivo","Actividades Extracurriculares (Proyección Social)",
         "Programación Paralela y Distributiva","Aprendizaje Profundo","Ingeniería de Software I","Redes de Computadoras II","Formulación de Proyectos de Tecnologías de Información","Electivo",
         "Seminario de Investigación","Electivo","Ingeniería de Software II","Sistemas de Internet de las Cosas","Ciberseguridad","Electivo",
         "Trabajo de Investigación","Actividades Extracurriculares (Debate)","Desarrollo de Proyectos de Ingeniería de Software","Práctica Pre-Profesional","Administración de Tecnologías de Información"]

Codigos= ["QUG01","CBG01","HIG01","FIG01","MEG01","MEG02",
          "IFI01","MEI04","IFG01","LCG01","MEG03","MEG04",
          "IFI02","IFI03","MEI06","FII02","MEI05","MEI09",
          "IFI04","IFI05","ADI01","ELI01","IFI07","MEI08",
          "IFI08","IFI09","IFI10","IFI11","IFI13","IFI12",
          "EUI01","IFI14","IFI15","IFI16","ELECTIVO","IFI17",
          "IFI22","IFI19","IFI20","IFI21","ELECTIVO","IFI23",
          "IFI24","IFI25","IFI26","IFI27","IFI28","ELECTIVO",
          "IFI29","ELECTIVO","IFI30","IFI31","IFI32","ELECTIVO",
          "IFI33","IFI18","IFI34","IFI66","IFI35"]
Semestres= [1,1,1,1,1,1,2,
            2,2,2,2,2,3,3,
            3,3,3,3,4,4,4,
            4,4,4,5,5,5,5,
            5,5,6,6,6,6,6,
            6,7,7,7,7,7,7,
            8,8,8,8,8,8,9,
            9,9,9,9,9,10,10,
            10,10,10,10]

Creditos= [4,3,3,4,4,4,
           3,4,3,4,4,4,
           4,2,4,4,4,4,
           4,2,4,4,4,4,
           4,2,4,4,4,4,
           2,4,4,4,4,4,
           3,4,5,4,4,2,
           4,4,4,4,3,3,
           3,4,4,4,4,3,
           4,2,4,8,4]

Areas= ["Estudios Generales","Estudios Generales","Estudios Generales","Estudios Generales","Estudios Generales","Estudios Generales",
        "Ciencias de la Computación","Ciencias de la Computación","Estudios Generales","Estudios Generales","Estudios Generales","Estudios Generales",
        "Ciencias de la Computación","Ciencias de la Computación","Ciencias de la Computación","Ingenieria Computacional","Ciencias de la Computación","Ciencias de la Computación",
        "Ciencias de la Computación","Ciencias de la Computación","Gestion","Ingenieria Computacional","Ciencias de la Computación","Ciencias de la Computación",
        "Ciencias de la Computación","Ciencias de la Computación","Ingenieria de Software","Ingenieria Computacional","Ciencias de la Computación","Ciencias de la Computación",
        "Actividades Extracurriculares","Inteligencia Artificial","Ingenieria de Software","Ingenieria Computacional","Electivos de Especialiad","Ciencias de la Computación",
        "Inteligencia Artificial","Inteligencia Artificial","Ingenieria de Software","Ingenieria Computacional","Electivos de Especialiad","Actividades Extracurriculares",
        "Ciencias de la Computación","Inteligencia Artificial","Ingenieria de Software","Ingenieria Computacional","Gestión","Electivos de Especialiad",
        "Investigación","Electivos de Especialiad","Ingenieria de Software","Ingenieria Computacional","Gestión","Electivos de Especialiad",
        "Investigación","Actividades Extracurriculares","Ingenieria de Software","Práctica Pre-Profesionales","Gestión"]

Cursosporsemestre = [
  [],
  ["\n- Química general\n- Ecología y Medio Ambiente\n- Historia Crítica del Perú e Identidad Nacional\n- Física I\n- Álgebra y Geometría Analítica\n- Cálculo I\n"],
  ["\n- Fundamentos de programación\n- Matemáticas Discretas I\n- Pensamiento Computacional e Inteligencia Artificial\n- Lingüística y Comunicación Humana\n- Estadística General\n- Cálculo II\n"],
  ["\n- Algoritmos y Estructura de Datos I\n- Programación I\n- Matemáticas Discretas II\n- Física Aplicada a la Informática\n- Álgebra Lineal Computacional\n- Cálculo III\n"],
  ["\n- Algoritmos y Estructura de Datos II\n- Programación II\n- Organización y Dirección de Empresas\n- Electrónica y Diseño Digital\n- Modelos Probabilísticos\n- Ecuaciones Diferenciales\n"],
  ["\n- Análisis y Diseño de Algoritmos\n- Programación III\n- Análisis y Diseño de Sistemas de Información\n- Organización y Arquitectura del Computador\n- Teoría de la Computación\n- Métodos Numéricos\n"],
  ["\n- Actividades Extracurriculares (Deportes)\n- Inteligencia Artificial\n- Fundamentos y Diseño de Bases de Datos\n- Sistemas Operativos\n- Electivo\n- Modelado y Simulación\n"],
  ["\n- Ciencia de Datos\n- Aprendizaje Automático\n- Metodología de Desarrollo de Software\n- Redes de Computadoras I\n- Electivo\n- Actividades Extracurriculares (Proyección Social)\n"],
  ["\n- Programación Paralela y Distributiva\n- Aprendizaje Profundo\n- Ingeniería de Software I\n- Redes de Computadoras II\n- Formulación de Proyectos de Tecnologías de Información\n- Electivo\n"],
  ["\n- Seminario de Investigación\n- Electivo\n- Ingeniería de Software II\n- Sistemas de Internet de las Cosas\n- Ciberseguridad\n- Electivo\n"],
  ["\n- Trabajo de Investigación\n- Actividades Extracurriculares (Debate)\n- Desarrollo de Proyectos de Ingeniería de Software\n- Práctica Pre-Profesional\n- Administración de Tecnologías de Información\n"]
]

"""####Módulos

Saludo Inicial
"""

def SaludoInicial():
  print("╔══════════════════════════════════════════════════╗")
  print("║               MALLABOT INFORMÁTICA               ║")
  print("║ Responde: código | créditos | área | semestre    ║")
  print("╚══════════════════════════════════════════════════╝")

  nombre = input("Hola 👋 ¿Cómo te llamas? : ").strip()
  print(f"\n✨ Bienvenido/a, {nombre}.\n")
  print("🤖 Yo soy Mallabot Informatica.")
  print("Te ayudo a consultar la malla curricular de Ing. Informática y de Sistemas.")
  print("Puedes preguntarme cosas como:")
  print("  • ¿Cuál es el código de Cálculo I?")
  print("  • ¿Cuántos créditos tiene Física I?")
  print("  • Quiero saber cursos por semestre")
  print("Escribe 'ayuda' si quieres ver más formas de preguntar.")
  print("Escribe 'salir' para terminar.\n")
  saludos = [ "Mucho gusto", "Encantado", "Bienvenido", "Saludos" ]
  print(random.choice(saludos) + ", " + nombre + "!")
  return nombre

"""Procesar de acuerdo a pregunta"""

def ProcesarCodigo(Curso, Indice):
  codigo=Codigos[Indice]
  return f"📌 El código de {Curso} es {codigo}"

def ProcesarSemestre(Curso, Indice):
  semestre=Semestres[Indice]
  return f"📍 '{Curso}' se dicta en el semestre {semestre}"

def ProcesarCreditos(Curso, Indice):
  creditos=Creditos[Indice]
  return f"✅ '{Curso}' tiene {creditos} créditos."

def ProcesarArea(Curso, Indice):
  areas=Areas[Indice]
  return f"🏷️  El curso '{Curso}' pertenece al área: {areas}."

def ProcesarCursosPorSemestre(Semestre):
  cursosporsemestre=Cursosporsemestre[Semestre]
  return f"📚  Los cursos del semestre {Semestre} son: \n{', '.join(cursosporsemestre)}"

def responder_pregunta(pregunta):
    pregunta=pregunta.lower()
    if ("curso" in pregunta or "cursos" in pregunta) and ("semestre" in pregunta or "ciclo" in pregunta):
      numerosemestre=int(input("Por favor, ingresa el semestre (número 1-10): "))
      return ProcesarCursosPorSemestre(numerosemestre)
    if "ayuda" in pregunta or "ejemplos" in pregunta:
      return (
  "🧭 Guía rápida:\n"
  "• Código:    ¿Cuál es el código de <curso>?\n"
  "• Créditos:  ¿Cuántos créditos tiene <curso>?\n"
  "• Área:      ¿A qué área pertenece <curso>?\n"
  "• Semestre:  ¿En qué semestre está <curso>?\n"
  "• Por semestre: Cursos por semestre \n"
  "\n"
  "🧠 Consejo: escribe el nombre del curso tal como aparece en la malla."
)
    for curso in reversed(Cursos):
        if curso.lower() in pregunta:
          indice=Cursos.index(curso)
          if "codigo" in pregunta or "código" in pregunta:
            return ProcesarCodigo(curso, indice)
          elif "semestre" in pregunta or "ciclo" in pregunta:
            return ProcesarSemestre(curso, indice)
          elif "creditos" in pregunta or "créditos" in pregunta:
            return ProcesarCreditos(curso, indice)
          elif "area" in pregunta or "área" in pregunta or "a qué área" in pregunta or "a que area" in pregunta:
            return ProcesarArea(curso, indice)
    return (
  "❌ No pude identificar el curso o la intención de tu pregunta.\n"
  "👆 Si quieres, puedes escribir 'ayuda' para ver ejemplos."
)

"""Saludo Final"""

def SaludoFinal(nombre):
  print('\n************************************************')
  print(f'✨ Ha sido un gusto interactuar contigo, {nombre} ✨')
  print('Si necesitas más, vuelve cuando quieras. ¡Éxitos!')
  print('************************************************')

"""###Programa principal"""

# -- Mostra saludo inicial
nombre=SaludoInicial()
# -- Interacción iterativa entre el programa y el usuario
pregunta=""
respuesta=""
while pregunta not in ["salir","adios","hasta la próxima","chao","SALIR","Salir"]:
    print("---------------------------------------------------\n")
    pregunta=input("👤 Tú: ")
    if pregunta.lower() not in ["salir","adios","hasta la próxima","chao","SALIR","Salir"]:
      respuesta="🤖 Sistema: " + responder_pregunta(pregunta)
      print(respuesta)
SaludoFinal(nombre)
